[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
if self.ability.name == 'Gros Michel' then G.GAME.pool_flags.gros_michel_extinct = true end
'''
position = "after"
payload = '''
if self.ability.name == 'Cavendish' then G.GAME.pool_flags.cavendish_extinct = true end
'''
match_indent = true